In [1]:
import numpy as np


In [3]:
chitra=np.array([10,30,78,98,99])
print("array:")
print(chitra)

array:
[10 30 78 98 99]


In [4]:
print("shape of array:")
print(chitra.shape)

shape of array:
(5,)


In [5]:
import pandas as pd

In [10]:
chittu=pd.Series([34,54,66,77,88])


In [11]:
print(chittu)


0    34
1    54
2    66
3    77
4    88
dtype: int64


In [12]:
d=np.array([23,34,45,55,77,88,89,98,34,45])
print("1 dimensional array:")
print(d)


1 dimensional array:
[23 34 45 55 77 88 89 98 34 45]


In [16]:
dhiya=np.array([[22,33,44,55,66],[32,43,54,65,57]])
print("values:")
print(dhiya)

values:
[[22 33 44 55 66]
 [32 43 54 65 57]]


In [22]:
s=np.ones((5,4))
print(s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [1]:
m=np.zeros((4,5))
print("zero")
print(m)

NameError: name 'np' is not defined